
server:
  port: 8888
  #  session-timeout: 60 # session 超时时间/分钟，默认是30
  #  tomcat:
  #    uri-encoding: utf-8 # 设置tomcat编码
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css,image/jpeg
spring:
  application:
    name: cloudManet
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  boot:
    admin:
      client:
        url: "http://wwww.youngbird97.top"
  datasource:
      name: druidDataSource
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat,wall,log4j,config
        max-active: 100
        initial-size: 1
        max-wait: 60000
        min-idle: 1
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: select 'x'
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-open-prepared-statements: 50
        max-pool-prepared-statement-per-connection-size: 20
        url: jdbc:mysql://localhost:3306/CloudManet?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
        username: root
        password: Yyj188706

  thymeleaf:
    cache: false
    prefix:  classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: utf-8
    mode: HTML
    #这个是关键，放开springboot对静态资源的拦截
    mvc:
      static-path-pattern: /static/**
    resources:
      static-locations: classpath:/templates/,classpath:/resources/,classpath:/resources/,classpath:/static/

# 开放健康检查接口
#  username: root  1.117.47.136
#    password: Yyj188706 yangyyj
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml # The path where the configuration mapper file is located
  type-aliases-package: com.complex.entity # Configure all class aliases under this package


Delcode:
  key: root
fileupload:
  path: http://fileserver.youngbird97.top/file/upload
localPath:
  path: /Users/birdyyoung/Desktop/upload/